apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: contactsdb
                   key: username
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: contactsdb
                   key: password
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"
